### ISSUE TITLE
1.13

### ISSUE THREAD

**Issue by maateh** [vik1395/ProtectionStones-Minecraft#36]
please update 1.13
worldguard version: the newest WorldGuard7.0.0
-------------------------------------

16:10:28 [INFO] ScoterZ issued server command: /ps
16:10:29 [ERROR] null
16:10:29 org.bukkit.command.CommandException: Unhandled exception executing command 'ps' in plugin ProtectionStones v1.4.4
16:10:29 at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.13-R0.1-SNAPSHOT-b1779.jar:git-Spigot-69774b3-8e87d03]
16:10:29 at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.13-R0.1-SNAPSHOT-b1779.jar:git-Spigot-69774b3-8e87d03]
16:10:29 at org.bukkit.craftbukkit.v1_13_R1.CraftServer.dispatchCommand(CraftServer.java:693) ~[spigot-1.13-R0.1-SNAPSHOT-b1779.jar:git-Spigot-69774b3-8e87d03]
16:10:29 at net.minecraft.server.v1_13_R1.PlayerConnection.handleCommand(PlayerConnection.java:1634) ~[spigot-1.13-R0.1-SNAPSHOT-b1779.jar:git-Spigot-69774b3-8e87d03]
16:10:29 at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1469) ~[spigot-1.13-R0.1-SNAPSHOT-b1779.jar:git-Spigot-69774b3-8e87d03]
16:10:29 at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13-R0.1-SNAPSHOT-b1779.jar:git-Spigot-69774b3-8e87d03]
16:10:29 at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13-R0.1-SNAPSHOT-b1779.jar:git-Spigot-69774b3-8e87d03]
16:10:29 at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13-R0.1-SNAPSHOT-b1779.jar:git-Spigot-69774b3-8e87d03]
16:10:29 at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_171]
16:10:29 at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_171]
16:10:29 at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [spigot-1.13-R0.1-SNAPSHOT-b1779.jar:git-Spigot-69774b3-8e87d03]
16:10:29 at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [spigot-1.13-R0.1-SNAPSHOT-b1779.jar:git-Spigot-69774b3-8e87d03]
16:10:29 at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot-1.13-R0.1-SNAPSHOT-b1779.jar:git-Spigot-69774b3-8e87d03]
16:10:29 at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot-1.13-R0.1-SNAPSHOT-b1779.jar:git-Spigot-69774b3-8e87d03]
16:10:29 at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-1.13-R0.1-SNAPSHOT-b1779.jar:git-Spigot-69774b3-8e87d03]
16:10:29 at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
16:10:29 Caused by: java.lang.NoSuchMethodError: com.sk89q.worldguard.bukkit.WorldGuardPlugin.getRegionManager(Lorg/bukkit/World;)Lcom/sk89q/worldguard/protection/managers/RegionManager;
16:10:29 at me.vik1395.ProtectionStones.Main.onCommand(Main.java:146) ~[?:?]
16:10:29 at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.13-R0.1-SNAPSHOT-b1779.jar:git-Spigot-69774b3-8e87d03]
16:10:29 ... 15 more

**Comment by jerzean** [comment]
1.13 has broke the plugin  im sorry but i dont know enough to recode the plugin for 1.13      mainly cause   worldguard no longer has the class/java/method .getRegionManager in worldgaurd 7.0   
the new way to get region info is incompatible with the old way    which means it needs alot to be rewritten
a temp fix that may work   is to use the last version of worldguard 6.*     
but until the api for worldguard 7.0 is posted im flying blind trying to fix it

**Comment by espidev** [comment]
I've submitted a pull request that updates the plugin to 1.13, as well as WorldGuard 7

**Comment by jerzean** [comment]
i cant merge pull requests   gonna have to wait till drag checks back @espidev   i also am working on a 1.13.1 version

**Comment by Dragoboss** [comment]
Already merged
